---

- name: "Install PostgreSQL Client and Ansible Requirements"
  package:
    name: 'postgresql{{ pgsql_major_version }}'
    state: present
  become: true

- name: "Install RHEL 7 PostgreSQL Client and Ansible Requirements"
  package:
    name: 
      - 'python-ipaddress'
      - 'python-psycopg2'
    state: present
  become: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

- name: "Create database user"
  postgresql_user:
    name: '{{ pgsql_user }}'
    password: '{{ pgsql_pass | default (omit) }}'
    encrypted: true
    state: present
  become_user: postgres
  become: true
  delegate_to: '{{ (pgsql_host == "localhost") | ternary (omit, pgsql_host) }}'
  when:
    - pgsql_host is defined
    - pgsql_user is defined

- name: "Create the database"
  postgresql_db:
    name: "{{ pgsql_name }}"
    owner: "{{ pgsql_user | default (omit) }}"
  become_user: postgres
  become: true
  delegate_to: '{{ (pgsql_host == "localhost") | ternary (omit, pgsql_host) }}'
  when:
    - pgsql_host is defined
    - pgsql_name is defined

- block:
  - name: "Get location of pg_hba.conf"
    command: >
      psql
        --tuples-only
        --pset=format=unaligned
        --command='show hba_file'
    changed_when: false
    check_mode: false
    become_user: postgres
    become: true
    register: hba_conf_path
    delegate_to: '{{ (pgsql_host == "localhost") | ternary (omit, pgsql_host) }}'

  - name: "Allow user access"
    postgresql_pg_hba:
      dest: '{{ hba_conf_path.stdout }}'
      contype: host
      address: "{{ pgsql_client_address | default ('samenet') }}"
      databases: '{{ pgsql_name }}'
      users: '{{ pgsql_user }}'
      state: present
    become: true
    delegate_to: '{{ (pgsql_host == "localhost") | ternary (omit, pgsql_host) }}'
    notify: Restart PostgreSQL

  # block:
  when:
    - pgsql_host is defined
    - pgsql_name is defined
    - pgsql_user is defined
    - pgsql_name != pgsql_user

# Another role may depend upon proper setting of pg_hba.conf
- meta: flush_handlers
