---

# name: Add PostgreSQL EL Repository
- import_tasks: repo.yml

- name: Install PostgreSQL Server (if requested)
  include_tasks: server.yml
  when: pgsql_server|bool

# name: Install PostgreSQL Client
- import_tasks: client.yml
