---

- name: "Install Postgres Repository"
  package:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-{{ ansible_machine }}/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  become: true
  when:
    - pgsql_major_version|length > 0
    - ansible_os_family == "RedHat"
