---

- name: "Install Postgres"
  package:
    name: [ 'postgresql{{ pgsql_major_version }}-server', 'python-psycopg2', 'python-ipaddress' ]
    state: present
  become: true
  notify:
    - Start PostgreSQL

- name: Install PostgreSQL (standalone)
  include_tasks: standalone.yml
  when: pgsql_primary is not defined

- name: Create PostgreSQL Streaming Replication (if requested)
  include_tasks: backup.yml
  when: pgsql_primary is defined
