---

- name: "Install Postgres Server"
  package:
    name:
      - 'postgresql-server'
      - 'python3-psycopg2'
      # - 'python-ipaddress'
    state: present
  become: true
  notify:
    - Start PostgreSQL

- name: Install PostgreSQL (standalone)
  include_tasks: standalone.yml
  when: pgsql_primary is not defined

- name: Create PostgreSQL Streaming Replication (if requested)
  include_tasks: backup.yml
  when: pgsql_primary is defined
