---

- name: Start PostgreSQL
  service:
    name: "{{ pgsql_service }}"
    state: started
    enabled: true
  become: true

- name: Restart PostgreSQL
  service:
    name: "{{ pgsql_service }}"
    state: restarted
  delegate_to: '{{ (pgsql_host == "localhost") | ternary (omit, pgsql_host) }}'
  become: true
